### ISSUE TITLE
The name of your script and repo is misleading. Please fix.

### ISSUE THREAD

**Issue by bongochong** [butteff/Ubuntu-Telemetry-Free-Privacy-Secure#5]
Ubuntu is not like Windows. Nothing you are removing can be considered telemetry, and Ubuntu does not ship with user data collection services that are on any level remotely similar to Windows. Ubuntu also allows you to turn off what little data it does collect (from bug reports and such) right in its own settings application.

1. You are misleading people about the operating system.
2. You are advertising a script that you barely understand, which can cause serious problems for less educated users that might make the foolish choice of running it.

Rename your script and repo to something like "Fuck-Up-My-Ubuntu-Installation", and then it will accurately reflect what's in it. Furthermore, sudo-ing more than once is unnecessary. Also, see here: https://github.com/butteff/Ubuntu-Telemetry-Free-Privacy-Secure/issues/4

STOP closing valid issues just because you don't understand debian and Ubuntu. Stop closing valid issues because you don't have a proper understanding of English.

**Comment by butteff** [comment]
>You are misleading people about the operating system.

**Comment by butteff** [comment]
>You are misleading people about the operating system.

But Zeitgeist is really telemetric tool. it keeps a database of which files you open and which applications you run. And snapd mark packages too. Vino is pre-installed VNC server. And so on - it all is dangerous. Even if something is not dangerous, but open the ports - it is kind of danger and should t obe closed by ufw or removed. I've just collected all info from google to one my script. And I use the script and nothing wrong with my installation here.

>You are advertising a script that you barely understand, which can cause serious problems for less educated users that might make the foolish choice of running it

I am doing it for pull requests, I want to have own system more hardened.

>Rename your script and repo to something like "Fuck-Up-My-Ubuntu-Installation"

You can do a fork and rename it. It is a github, you can do all, what you want.

>sudo-ing more than once is unnecessary and retarded

The script will be executed long time and in this time some bad software can possibly have access to system with the same rights (root), one checking for permissions doesn't give a warranty of sudo execution instead of "su root", every string with sudo - gives warranty of safety. Also, it is easy to copy only one command from list of the commands.

**Comment by bongochong** [comment]
Telemetry involves TRANSMITTING data to another destination outside of your own machine. This is not what zeitgeist does at all, on any level. You also do not understand what sudo does.
